default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: easy_school_api_development

test:
  <<: *default
  database: easy_school_api_test

production:
  <<: *default
  database: easy_school_api_production
  username: easy_school_api
  password: <%= ENV['EASY-SCHOOL-API_DATABASE_PASSWORD'] %>
